name: GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          lfs: true
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: 'pip'
          cache-dependency-path: '**/pyproject.toml'
      - name: Install apt dependencies
        run: |
          sudo apt-get update
          sudo apt-get -qq install exiftool libgdal-dev libzbar0t64
          GDAL_VERSION=$(gdal-config --version)
          pip install "gdal==$GDAL_VERSION"
      - name: Install dependencies
        run: pip install -e .[docs]
      - name: Build GitHub Pages site
        run: scripts/build_gh_pages.sh
      - uses: actions/upload-pages-artifact@v5
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v5
